---
 - hosts: localhost
   gather_facts: no
   vars_prompt:
      - name: x
        prompt: "enter the X value:"
        private: no
      - name: y
        prompt: "enter the Y value:"
        private: no
   
   tasks:
   - debug: 
       msg:
        - "The value of x: {{x}}"
        - "The value of y: {{y}}"
        - "{{x}} + {{y}} = {{x+y}}"
        - - "{{x}} + {{y}} = {{x|int+y|int}}"
