---
- hosts: all
  name: selinux enable or disable
  become: true
  vars:
    status: disabled
  tasks:
    - name: changing the config file
      lineinfile:
         path: /etc/selinux/config
         regexp: '^SELINUX='
         line: 'SELINUX={{ status }}'


