---
- name: copy executable script to remote location, execute script and get result
  hosts: all
  become: true

  tasks:
     - name: Transfer executable script script
       copy: src=/home/linc_ops/scripts/user_create_stratint_svc_fi.sh dest=/tmp/ mode=0777
 
     - name: Execute the script
       command: sh /tmp/user_create_stratint_svc_fi.sh
